import js from '@eslint/js';
import prettier from 'eslint-config-prettier';

export default [
  {
    ignores: ['node_modules/', 'src/public/'],
  },
  js.configs.recommended,
  prettier,
  {
    rules: {
      'no-unused-vars': 'warn',
      'no-undef': 'warn',
      'no-console': 'warn',
      'no-empty': 'warn',
      'no-extra-semi': 'warn',
      'no-redeclare': 'warn',
      'no-constant-condition': 'warn',
      'no-irregular-whitespace': 'warn',
      'no-unreachable': 'warn',
      'no-inner-declarations': 'warn',
      'no-prototype-builtins': 'warn',
      'no-useless-escape': 'warn',
      'no-fallthrough': 'warn',
      'no-case-declarations': 'warn',
      'no-async-promise-executor': 'warn',
      'no-cond-assign': 'warn',
      'no-compare-neg-zero': 'warn',
      'no-control-regex': 'warn',
      'no-debugger': 'warn',
      'no-dupe-else-if': 'warn',
      'no-dupe-keys': 'warn',
      'no-duplicate-case': 'warn',
      'no-ex-assign': 'warn',
      'no-func-assign': 'warn',
      'no-import-assign': 'warn',
      'no-invalid-regexp': 'warn',
      'no-loss-of-precision': 'warn',
      'no-misleading-character-class': 'warn',
      'no-nonoctal-decimal-escape': 'warn',
      'no-obj-calls': 'warn',
      'no-self-assign': 'warn',
      'no-sparse-arrays': 'warn',
      'no-unexpected-multiline': 'warn',
      'no-unsafe-finally': 'warn',
      'no-unsafe-optional-chaining': 'warn',
      'no-unused-labels': 'warn',
      'no-useless-catch': 'warn',
      'no-empty-character-class': 'warn',
      'no-extra-boolean-cast': 'warn',
      'no-useless-assignment': 'warn',
      'require-yield': 'warn',
      'use-isnan': 'warn',
      'valid-typeof': 'warn',
    },
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        console: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        exports: 'readonly',
        module: 'readonly',
        require: 'readonly',
      },
    },
  },
];
