#!/usr/bin/env python3
"""CLI helper for reading/writing AI configuration.

Called by the Express bridge (bridge.js) via subprocess:
    python config_cli.py dump      → print current config as JSON (keys masked)
    python config_cli.py update    → read JSON from stdin, write to settings.toml + .env
"""

import json
import sys
from pathlib import Path

# Ensure engine package is importable (cwd = packages/engine, src/ holds the code)
_engine_root = Path(__file__).resolve().parent
sys.path.insert(0, str(_engine_root / "src"))

from engine.config.ai_config import dump_ai_config  # noqa: E402

# Paths
_DOTENV_PATH = Path.home() / ".vexcode" / ".env"
_TOML_PATH = Path.home() / ".vexcode" / "settings.toml"

# Keys that should NEVER be written to .env (non-secret config)
_ENV_SKIP_KEYS = frozenset({
    "AI_PROVIDER", "AI_TEMPERATURE", "AI_MAX_TOKENS",
    "AI_RESOLVE_TIMEOUT_SECONDS", "AI_NAMING_TIMEOUT_SECONDS",
    "AI_MAX_RETRIES", "AI_REQUEST_COOLDOWN_SECONDS",
    "SEMGREP_RULES_PATH",
})

# Sentinel: masked key means "user did not change this field"
_MASKED = "••••••"


# ---------------------------------------------------------------------------
# dump
# ---------------------------------------------------------------------------

def _cmd_dump() -> None:
    """Print the merged AI config as JSON (keys masked)."""
    data = dump_ai_config()
    json.dump(data, sys.stdout)
    sys.stdout.write("\n")


# ---------------------------------------------------------------------------
# update
# ---------------------------------------------------------------------------

def _env_prefix(provider: str) -> str:
    """Return env-var prefix for a provider (mirrors ai_config._env_prefix)."""
    if provider == "9router":
        return "NINEROUTER"
    return provider.upper()


def _load_existing_env() -> dict[str, str]:
    """Read existing .env entries into a dict."""
    entries: dict[str, str] = {}
    if _DOTENV_PATH.exists():
        try:
            for line in _DOTENV_PATH.read_text(encoding="utf-8").splitlines():
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, _, val = line.partition("=")
                    entries[key.strip()] = val.strip()
        except OSError:
            pass
    return entries


def _write_env(entries: dict[str, str]) -> None:
    """Write a dict to the .env file (overwrite)."""
    _DOTENV_PATH.parent.mkdir(parents=True, exist_ok=True)
    lines = [f"{k}={v}" for k, v in sorted(entries.items()) if v]
    _DOTENV_PATH.write_text("\n".join(lines) + ("\n" if lines else ""), encoding="utf-8")


def _load_existing_toml() -> dict:
    """Read the existing settings.toml (excluding [ai] section)."""
    if not _TOML_PATH.exists():
        return {}
    try:
        import tomllib
        with _TOML_PATH.open("rb") as f:
            return tomllib.load(f)
    except Exception:
        return {}


def _toml_value(v) -> str:
    """Format a Python value as a TOML literal."""
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    # Escape backslashes and quotes in strings
    escaped = str(v).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _write_toml(settings: dict, ai_section: dict) -> None:
    """Write settings dict + ai section to settings.toml."""
    _TOML_PATH.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# VexCode Engine — User Configuration Overrides",
        "#",
        "# This file lives in ~/.vexcode/settings.toml and is merged on top of the",
        "# repo defaults (conf/settings.toml). Secrets (API keys) stay in .env.",
        "# Environment variables override all values at runtime.",
        "#",
        "# Auto-generated by config_cli.py — do not edit manually.",
        "",
    ]

    # Write non-ai sections first (preserves analysis thresholds etc.)
    for section, values in settings.items():
        if section == "ai":
            continue
        if isinstance(values, dict):
            lines.append(f"[{section}]")
            for k, v in values.items():
                lines.append(f"{k} = {_toml_value(v)}")
            lines.append("")

    # Write [ai] section
    lines.append("[ai]")
    lines.append(f"enabled = {_toml_value(ai_section.get('enabled', True))}")
    lines.append("")

    # [ai.providers.*]
    providers = ai_section.get("providers", {})
    if providers:
        for name, cfg in providers.items():
            lines.append(f"[ai.providers.{name}]")
            lines.append(f"enabled = {_toml_value(cfg.get('enabled', True))}")
            lines.append(f"requires_key = {_toml_value(cfg.get('requires_key', True))}")
            if cfg.get("model"):
                lines.append(f"model = {_toml_value(cfg['model'])}")
            if cfg.get("base_url"):
                lines.append(f"base_url = {_toml_value(cfg['base_url'])}")
            lines.append("")

    # [ai.agents.*]
    agents = ai_section.get("agents", {})
    if agents:
        for name, cfg in agents.items():
            lines.append(f"[ai.agents.{name}]")
            lines.append(f"provider = {_toml_value(cfg.get('provider', 'openai'))}")
            if cfg.get("model"):
                lines.append(f"model = {_toml_value(cfg['model'])}")
            lines.append(f"enabled = {_toml_value(cfg.get('enabled', True))}")
            lines.append("")

    _TOML_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _cmd_update() -> None:
    """Read JSON payload from stdin and persist to settings.toml + .env."""
    raw = sys.stdin.read()
    if not raw.strip():
        json.dump({"success": False, "error": "Empty input"}, sys.stdout)
        sys.stdout.write("\n")
        return

    try:
        payload = json.loads(raw)
    except json.JSONDecodeError as exc:
        json.dump({"success": False, "error": f"Invalid JSON: {exc}"}, sys.stdout)
        sys.stdout.write("\n")
        return

    # -- Update .env (secrets only) -----------------------------------------
    env_entries = _load_existing_env()

    providers = payload.get("providers", {})
    for name, cfg in providers.items():
        prefix = _env_prefix(name)
        api_key = cfg.get("api_key", "")
        # Masked sentinel → keep existing key unchanged
        if api_key == _MASKED:
            continue
        # Empty → remove key (disconnect)
        if not api_key:
            env_entries.pop(f"{prefix}_API_KEY", None)
            continue
        # Real key → write
        env_entries[f"{prefix}_API_KEY"] = api_key

    _write_env(env_entries)

    # -- Build TOML ai section (non-secret data) ----------------------------
    toml_providers: dict = {}
    for name, cfg in providers.items():
        toml_providers[name] = {
            "enabled": cfg.get("enabled", True),
            "requires_key": cfg.get("requires_key", True),
            "model": cfg.get("model", ""),
            "base_url": cfg.get("base_url", ""),
        }

    toml_agents: dict = {}
    for name, cfg in payload.get("agents", {}).items():
        toml_agents[name] = {
            "provider": cfg.get("provider", "openai"),
            "model": cfg.get("model", ""),
            "enabled": cfg.get("enabled", True),
        }

    ai_section = {
        "enabled": payload.get("enabled", True),
        "providers": toml_providers,
        "agents": toml_agents,
    }

    # Preserve non-ai TOML sections
    existing = _load_existing_toml()
    _write_toml(existing, ai_section)

    json.dump({"success": True, "message": "AI settings saved."}, sys.stdout)
    sys.stdout.write("\n")


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def main() -> None:
    if len(sys.argv) < 2:
        print("Usage: config_cli.py <dump|update>", file=sys.stderr)
        sys.exit(1)

    command = sys.argv[1]
    if command == "dump":
        _cmd_dump()
    elif command == "update":
        _cmd_update()
    else:
        print(f"Unknown command: {command}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
